### ISSUE TITLE
Change theme color

### ISSUE THREAD

**Issue by ryland-goldman** [ryland-goldman/quizza#32]
Perhaps #4e94fd? Maybe a different share (or even something besides blue)? Also need logo redesign if we do this.

**Comment by CollinWentzien** [comment]
#12DCB6

**Comment by ryland-goldman** [comment]
I'll install that color and we can see how it looks. Reopening since it still needs to be implemented. 

![quizza_tq](https://github.com/ryland-goldman/quizza/assets/48637662/a4fe3050-ef1a-469e-80d2-429b0ee2277c)

**Comment by ryland-goldman** [comment]
Just added the new color — what do you think? Still need to redesign homepage logo and background.

**Comment by Hufflepuffuser** [comment]
Use this color pallet (seafoam green):
![31837](https://github.com/ryland-goldman/quizza/assets/98370736/0b1e62d5-7b30-40b2-88f8-766098f5f65b)

**Comment by ryland-goldman** [comment]
Reopening because more contrast is necessary between white text and the background in light mode.

**Comment by ryland-goldman** [comment]
Changed to #0FBD9D
