### ISSUE TITLE
Sign in button has disappeared in classes if ur not signed in

### ISSUE THREAD

**Issue by CollinWentzien** [ryland-goldman/quizza#40]
bro read the title

**Comment by ryland-goldman** [comment]
Could not reproduce. Please send a screenshot, console log, and URL.
![IMG_0107](https://github.com/ryland-goldman/quizza/assets/48637662/d423bbf5-0071-4857-80ba-f003fb5d9b0d)

**Comment by CollinWentzien** [comment]
ctrl shift r the page it should make it disappear
<img width="1439" alt="Screenshot 2023-07-22 at 12 21 56 AM" src="https://github.com/ryland-goldman/quizza/assets/34798444/48029181-980d-486b-af13-669d0f9f6d12">

**Comment by ryland-goldman** [comment]
Does anything show up in the console? Also, send user agent.

**Comment by ryland-goldman** [comment]
Issue occurs if you dump caches before page load, appears to load `login.js` before GSI API.
