### ISSUE TITLE
title bar buttons dont work on other pages

### ISSUE THREAD

**Issue by CollinWentzien** [ryland-goldman/quizza#96]
for example on https://lghs.quizza.org/APCalcAB

**Comment by ryland-goldman** [comment]
Which buttons? The dropdown to change schools works for me, and sign in with google, and private sets, and sign out.

**Comment by CollinWentzien** [comment]
dropdown and sign in button dont work, try ctrl shift r

**Comment by ryland-goldman** [comment]
Please let me know what browser you are using. Also verify that you are not using a cached copy of the page.

**Comment by ryland-goldman** [comment]
No issue on Safari (cache disabled)

https://github.com/ryland-goldman/quizza/assets/48637662/bff4d5a4-19f1-45f4-ab6f-3e596b4c0a45

**Comment by ryland-goldman** [comment]
Are there any logs in the console?

**Comment by CollinWentzien** [comment]
https://github.com/ryland-goldman/quizza/assets/34798444/1c4a16e3-6d84-4320-aae7-e037618ef7d7

works for a sec after reloading but then stops, only on some pages though

**Comment by ryland-goldman** [comment]
I'm purging the Cloudflare cache. Try again in ~30 seconds.

**Comment by ryland-goldman** [comment]
I located a potential issue

    [GSI_LOGGER]: The given origin is not allowed for the given client ID.

**Comment by CollinWentzien** [comment]
still doesnt work

**Comment by ryland-goldman** [comment]
Pushed potential fix with commit f097ebb

**Comment by CollinWentzien** [comment]
it is working, well done
